SELECT 
	*,
	case when USAGE_TYPE='SMS' then 1 else 0 end SMS 
FROM 
(SELECT  
	case when isnull(MCDR.VAS_TYPE_CODE,'OTHERS') in ('SMS','DATA') then MCDR.VAS_TYPE_CODE else 'CALL' end as USAGE_TYPE, 
    MCDR.CALL_CODE, 
	MCDR.CALL_DIRECTION, 
	--ACCESS_METHOD_IDENTIFIER as MOBILE_NUMBER, 
	-CALL_SERVICE_TYPE_CODE as CALL_SERVICE_TYPE_CODE,
	CALL_COMPLETION_TYPE_CODE as TERMINATION_CODE,
	CALL_COMPLETION_REASON_CODE as TERMINATION_REASON, 
	--ORIGINATING_CELL_SITE_ID as CELL_SITE_ID, 
	--TERMINATING_CELL_SITE_ID as CELL_SITE_ID_2,
	FLAG_3G_2G, 
	CALL_CIRCLE_ID, 
	--GIS_LOCATION,
	--GIS_DISTRICT,
	--GIS_CATEGORY,
	CIRCLE_ID  as HOME_CIRCLE_ID, 
	PREPAID_FLAG, 
	--NETWORK_OPERATOR_CODE,
	--TERMINATING_OPERATOR_CODE, 
	--CALLING_NUMBER_OPERATOR_ID,
	--CALLED_NUMBER_OPERATOR_ID,
	ROAMING_IND as ROAMING, 
	CALL_START_DATE as USAGE_DATE, 
	CALL_START_HOUR as USAGE_HOUR, 
	CALL_LEG,
	CALL_DISTANCE,
	sum(CALL_DURATION) as DURATION,
	sum(CALL_DURATION) as CALL_DURATION
FROM 
	MSC left join
	MCDRCallCodes MCDR on MSC.CALL_CODE=MCDR.CALL_CODE left join 
	GISTABLE GIS on cast(MSC.ORIGINATING_CELL_SITE_ID as varchar)= GIS.CELL_SITE_ID 
group by 
	case when isnull(MCDR.VAS_TYPE_CODE,'OTHERS') in ('SMS','DATA') then MCDR.VAS_TYPE_CODE else 'CALL' end, 
    MCDR.CALL_CODE, 
	MCDR.CALL_DIRECTION, 
	-CALL_SERVICE_TYPE_CODE,
	CALL_COMPLETION_TYPE_CODE,
	CALL_COMPLETION_REASON_CODE, 
	--ORIGINATING_CELL_SITE_ID, 
	--TERMINATING_CELL_SITE_ID,
	FLAG_3G_2G, 
	CALL_CIRCLE_ID, 
	--GIS_LOCATION,
	--GIS_DISTRICT,
	--GIS_CATEGORY,
	CIRCLE_ID, 
	PREPAID_FLAG, 
	--NETWORK_OPERATOR_CODE,
	--TERMINATING_OPERATOR_CODE, 
	--CALLING_NUMBER_OPERATOR_ID,
	--CALLED_NUMBER_OPERATOR_ID,
	ROAMING_IND, 
	CALL_START_DATE, 
	CALL_START_HOUR, 
	CALL_LEG,
	CALL_DISTANCE
) v  

