SELECT 
	*,
	case when USAGE_TYPE='SMS' then 1 else 0 end SMS 
FROM 
(SELECT  
	'S'+ cast(cast(REC_SEQ_NUM as int) as varchar) as _id,
	case when isnull(MCDR.VAS_TYPE_CODE,'OTHERS') in ('SMS','DATA') then MCDR.VAS_TYPE_CODE else 'CALL' end as USAGE_TYPE, 
    MCDR.CALL_CODE, 
	MCDR.CALL_DIRECTION, 
	ACCESS_METHOD_IDENTIFIER as MOBILE_NUMBER, 
	-CALL_SERVICE_TYPE_CODE as CALL_SERVICE_TYPE_CODE,
	CALL_COMPLETION_TYPE_CODE as TERMINATION_CODE,
	CALL_COMPLETION_REASON_CODE as TERMINATION_REASON, 
	ORIGINATING_CELL_SITE_ID as CELL_SITE_ID, 
	TERMINATING_CELL_SITE_ID as CELL_SITE_ID_2,
	cast(case when ORIGINATING_CELL_SITE_ID != TERMINATING_CELL_SITE_ID then 1 else 0 end as int) MOVING, 
	FLAG_3G_2G, 
	CALL_CIRCLE_ID, 
	CIRCLE_ID  as HOME_CIRCLE_ID, 
	PREPAID_FLAG, 
	NETWORK_OPERATOR_CODE,
	TERMINATING_OPERATOR_CODE, 
	CALLING_NUMBER_OPERATOR_ID,
	CALLED_NUMBER_OPERATOR_ID,
	ROAMING_IND as ROAMING, 
	CALL_START_DATE as USAGE_DATE, 
	CALL_START_HOUR as USAGE_HOUR, 
	CALL_START_DATE + cast(cast(CALL_START_TIME as time) as datetime) as USAGE_TIME, 
	CALL_LEG,
	CALL_DISTANCE,
	CALL_DURATION as DURATION,
	CALL_DURATION
FROM 
	MSC left join
	MCDRCallCodes MCDR on MSC.CALL_CODE=MCDR.CALL_CODE
where ORIGINATING_CELL_SITE_ID='{0}') v  
