SELECT  
	'S'+ cast(cast(LOCAL_SEQUENCE_NO as int) as varchar) as _id,
	'DATA' as USAGE_TYPE, 
	ACCESS_METHOD_IDENTIFIER as MOBILE_NUMBER, 
	CAUSE_FOR_TERMINATION as TERMINATION_CODE, 
	CELL_IDENTIFIER as CELL_SITE_ID, 
	FLAG_3G_2G, 
	CALL_CIRCLE_ID, 
	HOME_CIRCLE_ID, 
	PREPAID_FLAG, 
    RATING_GROUP_ID, -- data related
	CALL_START_DATE as USAGE_DATE, 
	CALL_START_HOUR as USAGE_HOUR, 
	CALL_START_DATE + cast(cast(CALL_START_TIME as time) as datetime) as USAGE_TIME, 
	RESULT_CODE, -- date related
	ROAMING_ICR_INDICATOR as ROAMING,
	CALL_EVENT_DURATION as DURATION,
	DOWNLINK_VOLUME as VOLUME_DOWNLINK, 
	TOTAL_VOLUME as VOLUME, 
	UPLINK_VOLUME as VOLUME_UPLINK,
	CALL_EVENT_DURATION as VOLUME_DURATION 
FROM SASN